### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by frapell** [collective/collective.recaptcha#15]
@davisagli @smcmahon hey guys, could we get a new release of this package?

(or, you could give me access to https://pypi.python.org/pypi/collective.recaptcha and I can do it 👍 )

**Comment by davisagli** [comment]
@frapell I added you as an owner.

**Comment by gforcada** [comment]
@frapell is that release coming out anytime soon? 🙂

**Comment by frapell** [comment]
@gforcada New release 2.1.0 is out  :D
