### ISSUE TITLE
New release 2.x?

### ISSUE THREAD

**Issue by wesleybl** [collective/collective.recaptcha#35]
Can someone please create a new release of the [2.x branch](https://github.com/collective/collective.recaptcha/tree/2.x)?

Or can you give me permission at https://pypi.python.org/pypi/collective.recaptcha , so I can do it? My pypi user is `wesleybl`.

Thanks!

@davisagli @frapell @mpeeters @aclark4life @laulaz

**Comment by mpeeters** [comment]
I will do a new release today.

**Comment by frapell** [comment]
@wesleybl Gave you ownership on the package in pypi. Sorry I am unable to do a release for you right now...

**Comment by wesleybl** [comment]
> @wesleybl Gave you ownership on the package in pypi. Sorry I am unable to do a release for you right now...

@frapell I did release 2.1.1: https://pypi.org/project/collective.recaptcha/2.1.1

Thanks!

> I will do a new release today.
@mpeeters thank you for your promptness!
