### ISSUE TITLE
move @@recaptcha-settings to Plone control panel?

### ISSUE THREAD

**Issue by tkimnguyen** [collective/collective.recaptcha#9]
If this is going to be used in Plone sites only (as opposed to Zope generally) it would be nice to create a regular Plone control panel for this.

**Comment by idgserpro** [comment]
`install_requires` [asks for Plone](https://github.com/collective/collective.recaptcha/blob/aff85763550034e999d07d99c89d9f65ab677398/setup.py#L34) so I think is doable.

**Comment by tkimnguyen** [comment]
thx @frapell 💋  😃
